[tool.ruff]
line-length = 120
indent-width = 4

[tool.ruff.lint]
select = [
  "E", # pycodestyle
  "F", # Pyflakes
  "I", # isort
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
